name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when there's a push to the main branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x, 20.x, 22.x # Or another version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Configure Git
      - name: Configure Git for gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 5: Build the project and deploy using gh-pages
      - name: Build and Deploy to GitHub Pages
        run: npm run build
